services:
  web:
    build: .
    volumes:
      - .:/app
    command: python -m flask run --debug --host=0.0.0.0
    env_file: .env
    ports:
      - 8081:5000
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=password